[package]
name = "turbo-axum"
version = "0.3.0"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
description = "Hotwire Turbo helpers for axum"
homepage = "https://github.com/sajuthankappan/turbo-axum-rs"
repository = "https://github.com/sajuthankappan/turbo-axum-rs"
readme = "README.md"
keywords = ["hotwire", "turbo", "axum", "askama", "html"]
categories = ["web-programming::http-server", "template-engine"]
exclude = [".github/", "CLAUDE.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.16.0" }
askama_web = { version = "0.16.0", features = ["axum-0.8"] }
axum = { version = "0.8", features = ["macros"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
